name: General CI Build and Test

on: [push]

permissions:
  contents: read

jobs:
  RunTests:

    runs-on: ubuntu-latest
    container:
      image: verilator/verilator:v5.018

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
    - name: Print CPU Number
      run: |
        nproc
        lscpu
